task: "torchdriveenv"
keys: ["action"]
condition_keys: ["recurrent_state"]
data:
  train_data_dir: "data/itra_data"
  batch_size: 2
  dataloader_num_workers: 2
diffusion:
  n_step: 10
trainer:
  max_epochs: int = 20
  fast_dev_run: bool = True
  overfit_batches: float = 0.0
  lr: float = 0.0001
  optim_method: str = "SGD"
