task: "torchdriveenv"
diffusion_keys: ["action"]
condition_keys: ["recurrent_state"]
data:
  train_data_dir: "data/itra_data"
  val_data_dir: "data/itra_data"
  batch_size: 4096
  dataloader_num_workers: 2
model:
  h_dim: 128
  emb_dim: 32
  n_layers: 4
diffusion:
  n_steps: 10
trainer:
  max_epochs: 20000
  fast_dev_run: False
  overfit_batches: 0.0
  lr: 0.00001
  optim_method: "Adam"
